### PR TITLE
dissectors: hidpp: adds option to set initial HID++ version

### PR DESCRIPTION
**Pull request by FFY00**
This feels a little dirty, perhaps there's a better way to do this?

### CODE REVIEW

**Comment by FFY00** [comment]
@Lekensteyn could you have a look at this? Do you think there's a better way?

**Comment by FFY00** [comment]
I am going to merge this for the time being, @Lekensteyn please let me know if you have any suggestion.

**Comment by Lekensteyn** [comment]
This might not work properly in the following cases:
- A receiver is paired with a HID++ 1.0 device (e.g. K800) and a HID++ 2.0 device (e.g. M525).
- Multiple receivers are in use.

To solve the latter, I suggest including the device address in the key.
To solve the former, I suggest including the device index in the key.

While the C dissector API allows you to set "per-conversation" or "per-packet" metadata, this is not (yet?) possible in Lua. So using a global variable seems to be a reasonable workaround. You might want to clear the table in an "init routine" though, otherwise it'll also affect dissection of a different capture file. Something like this:
```
function hidpp_proto.init()
    hidpp_version_packets = {}
end
```

(In C there is a difference between a "cleanup" and "init routine", but in Lua the "init" function is called for both the "init routine" (called when a capture file is loaded) and a "cleanup routine" (called when a capture file is closed).

**Comment by FFY00** [comment]
Okay, this seems pretty easy. If you don't mind I will @ you once I make the changes :grin:.

**Pull request merged**
